# Generated by Django 5.1.6 on 2025-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_assets/default1.jpg', null=True, upload_to='event_assets'),
        ),
    ]
